title: Evas Blog
author: Eva Härich
email: eva.haerich@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a photographer, pianist, minimalist, daydreamer and passionated cyclist.

# social links
twitter_username: curiousave # DO NOT include the @ character, or else the build will fail!
github_username:  moodstudios_eva # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
